name: Matchbox
version: v1.5.0
slug: matchbox
description: Matchbox is a service that matches bare-metal machines to profiles that PXE boot and provision clusters.
url: https://gitlab.com/home-assistant-addons/home-assistant-matchbox
init: false
arch:
  - aarch64
  - amd64
image: registry.gitlab.com/home-assistant-addons/home-assistant-matchbox
map:
  - type: data
    path: /data
    read_only: false
  - type: addon_config
    path: /opt/matchbox
    read_only: false
ports:
  8080/tcp: 8000
  8081/tcp: 8081
environment:
  MATCHBOX_ADDRESS: 0.0.0.0:8080
  MATCHBOX_RPC_ADDRESS: 0.0.0.0:8081
  MATCHBOX_DATA_PATH: /opt/matchbox/data
  MATCHBOX_ASSETS_PATH: /opt/matchbox/data/assets
  MATCHBOX_CERT_FILE: /opt/matchbox/tls/server.crt
  MATCHBOX_KEY_FILE: /opt/matchbox/tls/server.key
  MATCHBOX_CA_FILE: /opt/matchbox/tls/ca.crt
  CLIENT_CERT_FILE: /opt/matchbox/tls/client.crt
  CLIENT_KEY_FILE: /opt/matchbox/tls/client.key
schema:
  ca.crt: str?
  server.crt: str?
  server.key: str?
  fqdn: str?
  arguments:
    - str
options:
  arguments:
    - -log-level debug
